export const SET_SELECTED_CATEGORY_ID = "SET_SELECTED_CATEGORY_ID";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";